name: 00-first workflow
on: 
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main 
  workflow_dispatch:
    inputs:
      branch: 
        description: 'Branch to test'
        type: string
        default: 'dev'
      input1:
        description: 'Input 1'
        type: string
        default: 'efg'
      input2:
        description: 'Input 2'
        type: number
        default: '123'
      
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    env:
      ENV_VAR1: 1234
      ENV_VAR2: "abcd"
      ENV_VAR3: ${{ github.event.inputs.input1 }}
      ENV_VAR3: ${{ github.event.inputs.input2 }}
    steps:
      - name: Trigger
        run: echo "Triggered by ${{github.event_name}} event"
      
      - name: Check Branch Input
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            if [ -z "${{ github.event.inputs.branch }}" ]; then
              echo "Branch input is required for manual trigger."
              exit 1
            else
              BRANCH_NAME="${{ github.event.inputs.branch }}" 
            fi
          else
            # Extract branch name from github.ref
            BRANCH_NAME="${{ github.ref }}" 
            BRANCH_NAME="${BRANCH_NAME##*/}"  # This removes everything before the last '/'
          fi
          echo "Checkout branch $BRANCH_NAME"
          
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          ref: "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}"
  
      - name: Log Current Branch and Commit
        run: |
          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Current commit: $(git rev-parse HEAD)"
      
      - name: Export ENV variable
        run: |
          echo ${{env.ENV_VAR1}}
          echo ${{env.ENV_VAR2}}
          echo ${{env.ENV_VAR3}}
          echo ${{env.ENV_VAR4}}
          export var1=${{ env.ENV_VAR1}}
          var2=${{env.ENV_VAR2}}
          echo "var1: $var1"
          echo "var2: $var2"
