name: Trigger Workflow B

on:
  pull_request:
    branches:
      - main  # Trigger khi có PR vào nhánh `main`
  workflow_dispatch:  # Cho phép trigger thủ công (manual trigger)
    inputs:
      branch_b:
        description: 'branch checkout b'
        required: true
jobs:
  trigger-workflow-b:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository A
        uses: actions/checkout@v4.2.2

      - name: Set up environment variables
        run: |
          echo "REPO_B_OWNER=SiliconLabsInternal" >> $GITHUB_ENV
          echo "REPO_B_NAME=DevS-SQA" >> $GITHUB_ENV
          echo "DEFAULT_BRANCH=debug-thvu" >> $GITHUB_ENV  # Default branch để checkout vào repo B
          echo "PARAM_1=value1" >> $GITHUB_ENV
          echo "PARAM_2=value2" >> $GITHUB_ENV
          echo "PARAM_3=value3" >> $GITHUB_ENV
          echo "PARAM_4=value4" >> $GITHUB_ENV
          echo "PARAM_5=value5" >> $GITHUB_ENV

          # Nếu trigger thủ công (manual), lấy branch của A từ github.ref
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "PR_BRANCH=${{ github.event.inputs.branch_b }}" >> $GITHUB_ENV 
          else
            echo "PR_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV  # Lấy branch của PR khi trigger qua PR
          fi

      - name: Trigger Workflow B on Repo B
        run: |
          response=$(curl -v -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.SILABS_THIEUVU_PAT }}" \
            -d '{
                  "ref": "refs/heads/${{ env.DEFAULT_BRANCH }}",
                  "inputs": {
                    "param_1": "${{ github.repository }}",
                    "param_2": "${{ env.PARAM_2 }}",
                    "param_3": "${{ env.PARAM_3 }}",
                    "param_4": "${{ env.PARAM_4 }}",
                    "param_5": "${{ env.PARAM_5 }}",
                    "param_6": "${{ env.PR_BRANCH }}"
                  }
                }' \
            https://api.github.com/repos/${{ env.REPO_B_OWNER }}/${{ env.REPO_B_NAME }}/actions/workflows/workflow-b.yml/dispatches)

          echo "Response: $response"

      - name: Check if Workflow B ran successfully
        run: |
          if echo "$response" | grep -q '"message": "Not Found"'; then
            echo "Error: Workflow or repository not found."
            exit 1
          fi
          if echo "$response" | grep -q '"status": "completed"'; then
            echo "Workflow B ran successfully!"
          else
            echo "Workflow B failed to start or complete."
            exit 1
          fi
