name: 01- Run TruffleHog Security Scan

on:
  workflow_dispatch:

jobs:
  trufflehog_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: "--version "
      - name: Save TruffleHog Report to JSON file
        run: |
          trufflehog git --json https://github.com/${{ github.repository }} > trufflehog_report.json
          
      - name: Upload TruffleHog Report
        uses: actions/upload-artifact@v4.3.4
        with:
          name: trufflehog-report
          path: trufflehog_report.json
