name: CI

on:
  pull_request:
    branches:
      - dev

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code from the PR
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        token: ${{ secrets.GH_PAT }}

    - name: Print Repository and Branch Info
      run: |
        echo "Repository: ${{ github.event.pull_request.head.repo.full_name }}"
        echo "Branch: ${{ github.event.pull_request.head.ref }}"
