name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Clone forked repo and fetch the PR branch
      run: |
        git clone https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git forked-repo
        cd forked-repo
        git fetch origin
        git checkout -b ${{ github.event.pull_request.head.ref }} origin/${{ github.event.pull_request.head.ref }}

    - name: Print Repository and Branch Info
      run: |
        cd forked-repo
        echo "Repository: ${{ github.event.pull_request.head.repo.full_name }}"
        echo "Branch: ${{ github.event.pull_request.head.ref }}"
        
    - name: Show the differences between head and base branch
      run: |
        cd forked-repo
        git fetch origin ${{ github.event.pull_request.base.ref }}
        git diff origin/${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }}
