name: CI

on:
  pull_request:
    branches:
      - dev

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add remote and fetch the PR branch
      env:
        GH_PAT: ${{ secrets.SILABS_THIEUVU_PAT }}
      run: |
        git remote add forked https://github.com/${{ github.event.pull_request.head.repo.full_name }}
        git fetch forked
        git checkout -b ${{ github.event.pull_request.head.ref }} forked/${{ github.event.pull_request.head.ref }}

    - name: Print Repository and Branch Info
      run: |
        echo "Repository: ${{ github.event.pull_request.head.repo.full_name }}"
        echo "Branch: ${{ github.event.pull_request.head.ref }}"
